package actions

const PLAYER_HEALTH  = 100
const MONSTER_HEALTH  = 100
const PLAYER_ATTACK_MIN_DMG = 5
const PLAYER_ATTACK_MAX_DMG = 10
const PLAYER_ATTACK_MIN_DMG_SPECIAL = 10
const PLAYER_ATTACK_MAX_DMG_SPECIAL = 20
const PLAYER_HEAL_MIN = 10
const PLAYER_HEAL_MAX = 20
const MONSTER_ATTACK_MIN=9
const MONSTER_ATTACK_MAX=13